project:
  type: website
  output-dir: docs

website:
  title: "Sarem Seitz"
  navbar:
    right:
      - about.qmd
      - notebooks.qmd
      - notes.qmd
      - icon: github
        href: https://github.com/SaremS
      - icon: twitter
        href: https://twitter.com/sarem_seitz
format:
  html:
    theme: cosmo
    css: styles.css



