version: '3.7'

networks:
  kafka-zookeeper-network:
    driver: bridge
  kafka-backend-network:
    driver: bridge
  middleware-network:
    driver: bridge
  frontend-network:
    driver: bridge
  
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - middleware-network
      - frontend-network
    restart: on-failure
    depends_on:
      - middleware

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-zookeeper-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
    networks:
      - kafka-zookeeper-network
      - kafka-backend-network
    restart: on-failure

  python-stream:
    container_name: python-stream
    depends_on:
      - kafka
      - zookeeper
    build:
      context: ./services/python-stream
      dockerfile: Dockerfile
    env_file: ./services/python-stream/.env
    restart: on-failure
    networks:
      - kafka-backend-network
  
  sentiment-stream:
    container_name: sentiment-stream
    depends_on:
      - kafka
      - zookeeper
      - python-stream
    build:
      context: ./services/sentiment-stream
      dockerfile: Dockerfile
    env_file: ./services/sentiment-stream/.env
    restart: on-failure
    volumes:
      - "./services/sentiment-stream/saved_model:/sentimenter/saved_model"
    networks:
      - kafka-backend-network

  middleware:
    container_name: middleware
    depends_on:
      - kafka
      - zookeeper
      - python-stream
    build:
      context: ./services/kafka-middleware
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - middleware-network
      - kafka-backend-network
    env_file: ./services/kafka-middleware/.env
    volumes:
      - "./services/kafka-middleware/persist:/kafka-middleware/persist"