apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: middleware
  name: middleware
spec:
  ports:
    - name: "9988"
      port: 9988
      targetPort: 9988
  selector:
    service-name: middleware
status:
  loadBalancer: {}
