apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service-name: middleware
  name: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      service-name: middleware
  template:
    metadata:
      labels:
        service-name: middleware
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER
          value: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092
        - name: SERVER_ADDRESS
          value: 0.0.0.0:9988
        image: ghcr.io/sarems/blog/kafka-middleware:{{ .Values.image.version }}
        name: middleware
        volumeMounts:
        - mountPath: /kafka-middleware/persist
          name: blog-middleware-pvc
      imagePullSecrets:
      - name: blogpullsecret
      restartPolicy: Always
      volumes:
      - name: blog-middleware-pvc
        persistentVolumeClaim:
          claimName: blog-middleware-pvc

