apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-stream-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
status: {}
