apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: static-files
  name: static-files
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service-name: static-files
status:
  loadBalancer: {}
