#Frontend Nginx - serve static files and link services
FROM nginx:1.22-alpine
RUN apk update && apk add bash

COPY ../docs/ /www/data/
COPY ../widgets/*/dist/ /www/data/widgets/
COPY ./nginx_static.conf /etc/nginx/nginx.conf


EXPOSE 80