apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/kafka-frontend-network: "true"
    io.kompose.network/middleware-network: "true"
    io.kompose.service: middleware
  name: middleware
spec:
  containers:
    - env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              key: KAFKA_BROKER
              name: environment--env-kafka-middleware
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: SERVER_ADDRESS
              name: environment--env-kafka-middleware
      image: ghcr.io/sarems/blog/showcases-kafka-middleware:latest
      name: middleware
      resources: {}
      volumeMounts:
        - mountPath: /kafka-middleware/persist
          name: middleware-claim0
  restartPolicy: OnFailure
  volumes:
    - name: middleware-claim0
      persistentVolumeClaim:
        claimName: middleware-claim0
status: {}
