apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/kafka-backend-network: "true"
    io.kompose.service: python-stream
  name: python-stream
spec:
  containers:
    - env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              key: KAFKA_HOST
              name: environment--env-python-stream
        - name: REDDIT_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: REDDIT_CLIENT_ID
              name: environment--env-python-stream
        - name: REDDIT_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: REDDIT_CLIENT_SECRET
              name: environment--env-python-stream
      image: ghcr.io/sarems/blog/python-stream:latest
      name: python-stream
      resources: {}
  restartPolicy: OnFailure
status: {}
