name: Deploy python stream
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'services/python-stream/**'
    - '.github/workflows/deploy_python_stream.yml'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2.5.0 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.PUSH_IMAGE_KEY }}     
          image-name: blog-python-stream
          build-context: services/python-stream
          dockerfile: services/python-stream/Dockerfile

  #deploy:
  #  name: Deploy
  #  runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/master'
  #  needs: build-and-publish
  #  steps:
  #  - name: executing remote ssh commands using password
  #    uses: appleboy/ssh-action@v0.1.6
  #    with:
  #      host: ${{ secrets.DEPLOY_HOST }}
  #      username: ${{ secrets.DEPLOY_USERNAME }}
  #      password: ${{ secrets.DEPLOY_PASSWORD }}
  #      port: ${{ secrets.DEPLOY_PORT }}
  #      script: |
  #        cd showcases
  #        git pull origin master
  #        docker-compose pull
  #        export SENTIMENT_STREAM_NODE=${{ secrets.SENTIMENT_STREAM_NODE }}
  #        export KAFKA_MIDDLEWARE_NODE=${{ secrets.KAFKA_MIDDLEWARE_NODE }}
  #        docker stack up -c docker-compose.yml showcases
