name: Deploy sentiment stream
on:
  workflow_dispatch:
  push:
    tags:
      - "*"


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: services/sentiment-stream
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v3
        with: 
          path: services/sentiment-stream/venv
          key: ${{ runner.os }}-${{ hashFiles('sentiment-stream/requirements.txt') }}

      - name: Create venv
        if: steps.cache-venv.cache-hit != 'true'
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Cache model
        id: cache-model
        uses: actions/cache@v3
        with: 
          path: services/sentiment-stream/saved_model
          key: ${{ runner.os }}-saved-model

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover



  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.5.0 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.PUSH_IMAGE_KEY }}     
          image-name: sentiment-stream
          extract-git-tag: true
          build-context: ./services/sentiment-stream
          dockerfile: ./services/sentiment-stream/Dockerfile
          
