name: Deploy python stream
on:
  release:
    types: [published]


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.PUSH_IMAGE_KEY }}     
          image-name: blog-python-stream
          extract-git-tag: true
          build-context: services/python-stream
          dockerfile: services/python-stream/Dockerfile
