name: Render and deploy
on:
  release:
    types: [published]

jobs:
  quarto-render-and-push:
    name: Render
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0 # Checking out the repo
        
    - name: Set Up WASM
      uses: actions/checkout@v2
    - name: Build WASM modules
      run: |
        cd wasm_modules
        for d in */ ; do
          cd $d
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cargo test
          wasm-pack build --target web
          cd ..
        done
        cd ..
      
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - name: Build widgets
      run: |
        cd widgets
        for d in */ ; do
          cd $d
          npm install 
          npm run build:widget
          cd ..
        done
        cd ..
        
    - name: Set up quarto
      uses: quarto-dev/quarto-actions/setup@v2
      
    - name: Render
      uses: quarto-dev/quarto-actions/render@v2
    
    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.PUSH_IMAGE_KEY }}     
        image-name: blog
        extract-git-tag: true
        build-context: .
        dockerfile: ./Dockerfile    
        
